openapi: 3.0.3
info:
  title: Offset-Based Proxy API
  version: 1.0.0
  description: A proxy API that provides limit/offset pagination and maps to a token-based backend API.
servers:
  - url: http://localhost:4000

paths:
  /fdx-items:
    get:
      summary: Retrieve items using FDX-style offset/limit pagination
      parameters:
        - name: limit
          in: query
          description: Number of items to return
          schema:
            type: integer
            default: 10
        - name: offset
          in: query
          description: The index of the first item to return
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: A paginated list of items
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    example: 1000
                  offset:
                    type: integer
                    example: 20
                  limit:
                    type: integer
                    example: 10
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
        '401':
          description: Unauthorized
        '416':
          description: Offset exceeds data bounds
      security:
        - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
